import React from 'react';
import './ContributionDetails.css';

const ContributionDetails = () => {
  return (
    <div className="contribution-container">
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '2rem' }}>
        <h2 className="section-title" style={{ marginBottom: 0 }}>Contribution Details</h2>
        <a 
          href="https://github.com/K-Means-Technologoies-Pvt-Ltd/Behavior_Analytics_Framework_of_PiViTeL/tree/main/contributions" 
          target="_blank" 
          rel="noopener noreferrer"
          style={{
            display: 'inline-block', padding: '0.5rem 1rem', 
            backgroundColor: 'var(--card-bg)', border: '1px solid var(--border)',
            borderRadius: '0.5rem', color: 'var(--text-primary)', textDecoration: 'none',
            fontSize: '1rem', transition: 'all 0.3s ease'
          }}
        >
          View on GitHub
        </a>
      </div>

      <div className="contributors-grid">
        <div className="contributor-section">
          <h3 className="contributor-name">Jenish A. Borah</h3>
          <ul className="task-list">
            <li>
              <strong>Task 1: Raw Telemetry Data Collection</strong>
              <p>Collected raw telemetry CSV files generated by the PiViTeL edge device. Verified attributes such as timestamp, vehicle_speed, object_class, detection_confidence, etc.</p>
            </li>
            <li>
              <strong>Task 3: Dataset Structure Inspection</strong>
              <p>Inspected the merged telemetry dataset to verify structure, column types, dimensions, and missing values.</p>
            </li>
            <li>
              <strong>Task 4.2: Missing Value Treatment and Dataset Cleaning</strong>
              <p>Handled missing values to maintain temporal continuity. Removed empty overlay metadata, applied logical defaults for missing object detections, and used interpolation/filling for GPS signals.</p>
            </li>
            <li>
              <strong>Task 5: Descriptive Analysis of Feature Dataset</strong>
              <p>Performed statistical summaries, central tendency analysis, variability analysis, and identified event percentages like overspeed and close object risk.</p>
            </li>
            <li>
              <strong>Task 7: Bivariate Analysis of Driving Behaviour Dataset</strong>
              <p>Analyzed relationships between variables (e.g., Speed vs Distance, Risk Probability vs Speed) and generated pairplots, heatmaps, and scatter plots.</p>
            </li>
            <li>
              <strong>Task 9: Feature Selection</strong>
              <p>Identified relevant features influencing driving risk. Removed redundant/multicollinear features and prepared a clean optimized dataset for machine learning models.</p>
            </li>
          </ul>
        </div>

        <div className="contributor-section">
          <h3 className="contributor-name">Shruti Sarma</h3>
          <ul className="task-list">
            <li>
              <strong>Task 2: CSV Dataset Merging</strong>
              <p>Merged multiple PiViTeL telemetry CSV files collected from different driving sessions into a single consolidated dataset.</p>
            </li>
            <li>
              <strong>Task 4.1: Missing Value Investigation and Categorization</strong>
              <p>Analyzed the dataset to identify missing values. Categorized them into completely missing metadata, object detection missing values, GPS signal gaps, and telemetry measurement delays.</p>
            </li>
            <li>
              <strong>Task 5.0: Feature Engineering for Driving Behaviour Analytics</strong>
              <p>Transformed raw telemetry into meaningful features such as speed_change, accel_change, overspeed_event, sudden_braking, and close_object_event to detect risky driving.</p>
            </li>
            <li>
              <strong>Task 6: Univariate Analysis of Driving Behaviour Dataset</strong>
              <p>Analyzed individual variables to understand distribution. Created histograms, boxplots, pie charts, and GPS route visualizations to study driving patterns.</p>
            </li>
            <li>
              <strong>Task 8: Correlation Analysis</strong>
              <p>Analyzed relationships between variables in the telemetry dataset to identify dependencies and significant features influencing driving risk.</p>
            </li>
          </ul>
        </div>
      </div>

      <div className="common-task-section" style={{ marginTop: '2rem' }}>
        <h3 className="section-title" style={{ fontSize: '1.5rem', marginBottom: '1rem', borderBottom: 'none' }}>Common Tasks</h3>
        <div className="card" style={{ display: 'flex', gap: '1rem', flexWrap: 'wrap' }}>
          <span style={{ background: 'rgba(59, 130, 246, 0.1)', color: '#3b82f6', padding: '0.5rem 1rem', borderRadius: '0.5rem', fontWeight: 'bold' }}>Documentation</span>
          <span style={{ background: 'rgba(16, 185, 129, 0.1)', color: '#10b981', padding: '0.5rem 1rem', borderRadius: '0.5rem', fontWeight: 'bold' }}>Model Training</span>
          <span style={{ background: 'rgba(168, 85, 247, 0.1)', color: '#a855f7', padding: '0.5rem 1rem', borderRadius: '0.5rem', fontWeight: 'bold' }}>Building UI</span>
          <span style={{ background: 'rgba(239, 68, 68, 0.1)', color: '#ef4444', padding: '0.5rem 1rem', borderRadius: '0.5rem', fontWeight: 'bold' }}>Making PPT</span>
        </div>
      </div>
    </div>
  );
};

export default ContributionDetails;
