import React from 'react';
import './DatasetOverview.css';

const DatasetOverview = () => {
  return (
    <div className="dataset-overview-container">
      <h2 className="section-title">Dataset Overview</h2>
      
      <div className="cards-grid">
        <div className="card">
        <h3>1. Raw CSV Files</h3>
        <p>The following raw telemetry datasets have been collected directly from the PiViTeL device and are available for download:</p>
        <ul className="file-list">
          <li>
            <a href="/data/raw/driving_video.csv" target="_blank" rel="noreferrer">
              driving_video.csv
            </a> (474 KB) - Contains object detection and bounding box telemetry.
          </li>
          <li>
            <a href="/data/raw/sesor_data.csv" target="_blank" rel="noreferrer">
              sesor_data.csv
            </a> (517 KB) - Contains raw IMU, GPS, and timestamp details.
          </li>
        </ul>
      </div>

      <div className="card">
        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '1rem' }}>
          <h3 style={{ borderBottom: 'none', marginBottom: 0, paddingBottom: 0 }}>2. Cleaned & Merged Dataset</h3>
          <div style={{ display: 'flex', gap: '0.5rem' }}>
            <a href="https://github.com/K-Means-Technologoies-Pvt-Ltd/Behavior_Analytics_Framework_of_PiViTeL/blob/main/analytics/merge_datasets.py" target="_blank" rel="noopener noreferrer" className="see-code-btn">
              Merge Code
            </a>
            <a href="https://github.com/K-Means-Technologoies-Pvt-Ltd/Behavior_Analytics_Framework_of_PiViTeL/blob/main/analytics/missing_value_treatment.py" target="_blank" rel="noopener noreferrer" className="see-code-btn">
              Cleaning Code
            </a>
          </div>
        </div>
        <p className="description">
          The raw telemetry datasets were merged and thoroughly cleaned to maintain temporal continuity. Missing overlay metadata columns were removed completely. For object detections, frames without detected objects were replaced with logical defaults. GPS gaps were handled using advanced interpolation, ensuring chronological ordering throughout the trip.
        </p>
        <ul className="file-list">
          <li>
            <a href="/data/processed/pivitel_cleaned_dataset.csv" target="_blank" rel="noreferrer">
              pivitel_cleaned_dataset.csv
            </a> (1.44 MB) - Final dataset ready for feature engineering and modeling.
          </li>
        </ul>
      </div>

      <div className="card">
        <h3>3. Dataset Statistics</h3>
        <table className="stats-table">
          <tbody>
            <tr>
              <td><strong>Total Rows</strong></td>
              <td>4,398</td>
            </tr>
            <tr>
              <td><strong>Total Columns</strong></td>
              <td>47</td>
            </tr>
            <tr>
              <td><strong>Total Duration</strong></td>
              <td>Multiple trips logged</td>
            </tr>
          </tbody>
        </table>
        <p className="description">
          The dataset contains telemetry observations generated by the PiViTeL edge device, including information related to object detection, GPS coordinates, inertial sensor measurements, and temporal metadata.
        </p>
      </div>

      <div className="card">
        <h3>4. Data Quality & Missing Values</h3>
        <p className="description">
          Object detection attributes contain missing values in 1,098 rows (which occur when no object was detected). Several overlay metadata columns contain 100% missing values (optional metadata not recorded). GPS parameters have minor missing gaps due to temporary signal loss. IMU sensor measurements show 0 missing values, indicating consistent recording.
        </p>
      </div>
      </div>
    </div>
  );
};

export default DatasetOverview;
